/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(spectrumDetector.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(0)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/specdetect/spectrumDetector.h>
// pydoc.h is automatically generated in the build directory
#include <spectrumDetector_pydoc.h>

void bind_spectrumDetector(py::module& m)
{

    using spectrumDetector    = gr::specdetect::spectrumDetector;


    py::class_<spectrumDetector, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<spectrumDetector>>(m, "spectrumDetector", D(spectrumDetector))

        .def(py::init(&spectrumDetector::make),
           D(spectrumDetector,make))
        
        .def("set_center_freq",
         &spectrumDetector::set_center_freq,
         py::arg("freq"))


        ;




}








